index:
    path: /
    methods: ["GET"]
    controller: App\Controller\DefaultController::index

bonjour:
    path: /bonjour/{prenom}
    methods: ["GET"]
    controller: App\Controller\DefaultController::bonjour

login :
    path: /login
    methods: ["GET", "POST"]
    controller: App\Controller\LoginController::index

oublipass :
    path: /oublipass
    methods: ["GET", "POST"]
    controller: App\Controller\OubliPassController::index

resetpass :
    path: /resetpass
    methods: ["GET", "POST"]
    controller: App\Controller\ResetPassController::index

app_logout:
    path: /logout
    methods: GET


